twig:
  file_name_pattern: "*.twig"
  form_theme: ["form-theme.html.twig"]
  paths:
    "%kernel.project_dir%/email/css": email_css
    "%kernel.project_dir%/email/templates": email_templates

when@test:
  twig:
    strict_variables: true
